### ISSUE TITLE
Documentation Project submission

### ISSUE THREAD

**Issue by BacLuc** [ase-23-the-bald-owls/swiss-card-exchange#57]
# Contents

You need to wrap up everything you produced. We need a *Markdown* `README.md` document as a reference/instructions for your entire submission. You are free to attach any additional files you believe would be useful, but please insert their references to `README.md`.

Hopefully, you have organized everything into a *wiki* already. If you did so, please give some indications in the instructions file (`README.md`).

<aside>
🔑 The keyword here is **motivation**: if you made a choice, please specify a motivation for it.

</aside>

## 💻 Source code

For the **source code**, you have to freeze the repositories you produced. First, create a tag for your repositories marking a release for the project. Then, if you are on *GitHub*, you can easily export an archive file with everything packed. Otherwise, you can use the following command:

```bash
git archive ${COMMIT} --format zip --output ${FILE_PATH}.zip
```

This part should include only the code, not the repository history.

## 🌳 Repository

As you did for the other deliverables, you need to submit the state of your git repository containing the implementation for this deliverable and its history. The git repository should be submitted in its entirety, including the history of all branches since its creation.

Please, report also the links to the repositories. If private, grant us access.

## 👪 Project organization

We need to understand how you, as a group, scheduled the *tasks* for your project. Since you were asked to use an adapted *Scrum* methodology, we need to understand what you did exactly.
You can attach screenshots of the *Scrum*/*Kanban* boards you used. It is important that you let us know the process you applied. Please, report a timeline that gives an overview of the development. You can use a *Gantt chart*, for instance.

Also, we need to understand *how* you organized the *versioning* of your code. One suggestion is to extract the git branching graph and put some description on the model for branching you used, if any.

Finally, report on the use of *pull requests* you were asked to use. We need to understand how you took advantage of them.

If you reported the above-mentioned information as part of the *wiki*, just mention that.

## 📝 Documentation

We need documentation of the whole overview since you should have organized everything in *microservices*. Anything useful to better understand your code will be appreciated. Also, mention the use of specific technologies and their motivation.

As for single microservices, we expect to find a `README.md` file in the root of any repositories you used. Also, you should have documented the source code, thus report the way you did it, such as which *documentation generator* you used if any. Finally, report the documentation for the API.

Please, include the link to the wiki you produced.

## 🏃 How to run it

Consider this part of the submission as the description of the way to run everything in production.

Since you were asked to put every service in separate containers, they have to be buildable and runnable. Thus, we expect to find the `Dockerfile` and `docker-compose.yml` files to run the whole application.

Of course, exceptions may occur in the case of particular applications. For instance, there could also be the case that you built a mobile application, therefore report everything you find useful in this regard.

## 🧪 Testing and continuous integration

The *testing* was part of your job. Report everything useful to describe the way you planned and performed the testing of your code.

Also, we need information about the *continuous integration* flow you applied. Testing was probably part of it, thus you can decide to describe it here. Also, mention any *quality check* steps you applied and if you took that into consideration during the development.

# Submission

Submit your deliverable’s archive `<TeamName>_Project.zip` to the assessments area on Microsoft Teams.

- [x] ase-23-the-bald-owls/swiss-card-exchange#51
- [x] ase-23-the-bald-owls/swiss-card-exchange#56
- [x] ase-23-the-bald-owls/swiss-card-exchange#55
- [x] ase-23-the-bald-owls/swiss-card-exchange#54
- [x] ase-23-the-bald-owls/swiss-card-exchange#52
